### ISSUE TITLE
搜尋設定增加搜尋欄位

### ISSUE THREAD

**Issue by yeh19921026** [scarwu/MHWCalculator#10]
能不能在搜尋設定的地方增加搜尋欄為方便搜尋
因為某些原因例如MR不夠所以可能某些龍還不能打到想要移除
或是四洞珠還沒有齊全所以想調整 可是裡面太多東西
所以如果有搜尋欄位的話會方便很多

**Comment by scarwu** [comment]
這是個好建議，已經更新上去了。
