### ISSUE TITLE
TODO-2

### ISSUE THREAD

**Issue by scarwu** [scarwu/MHWCalculator#2]
1. 排除珠子
2. 英文翻譯 (w. Crawler)
3. 日文翻譯 (w. Crawler)
4. 候選套裝排序
5. 使用 flex 取代 bootstrap grid

**Comment by scarwu** [comment]
1. 排除珠子
2. 絢輝龍新武器補完
3. 排除武器後固定類型

**Comment by scarwu** [comment]
1. 歷戰絢輝龍武器
2. 英文翻譯 (w. Crawler)
3. 日文翻譯 (w. Crawler)

**Comment by alibudda** [comment]
絢輝龍武器中似乎少了鎧羅大槌．睡眠

**Comment by scarwu** [comment]
是的絢輝龍的武器之後會更新上去。
