### ISSUE TITLE
Deployed page not working

### ISSUE THREAD

**Issue by tcritically** [scarwu/MHWCalculator#36]
Deployed page on scar.tw and when I try to deploy personally are blank, when examining console, find that "mhwc:2020:8:sys:lang" in local storage is being set to "undefined" which prevents the page from loading.
![image](https://user-images.githubusercontent.com/7433911/219990787-f8f746fd-2a25-4b86-9836-17990f8c3126.png)

**Comment by scarwu** [comment]
Hi, thanks for your feedback. 
I've fixed this issue.
