### ISSUE TITLE
the calculator only pick helm waist and chest parts

### ISSUE THREAD

**Issue by wuminorb** [scarwu/MHWCalculator#6]
Great work！But after last release, it's seems the calculator only pick helm waist and chest parts.

**Comment by scarwu** [comment]
Hi, is this problem is same now?

**Comment by wuminorb** [comment]
They work perfect now, good job!

**Comment by wuminorb** [comment]
Hi, this problem comes up again since last night

**Comment by scarwu** [comment]
Hi, do you have any logs in browser console or how to operate MHWC?
Please let me know what happened.

**Comment by wuminorb** [comment]
Seems like you can't add set skills.

### without set skill:
![image](https://user-images.githubusercontent.com/10877837/53356436-624a6180-3966-11e9-99ae-f6b053b9a5dd.png)

### with set skills:
- 
![image](https://user-images.githubusercontent.com/10877837/53356541-9d4c9500-3966-11e9-900e-32ea6e3b3cdd.png)
- 
![image](https://user-images.githubusercontent.com/10877837/53356651-d38a1480-3966-11e9-9c4d-451b485a844a.png)
